package com.netflexity.amq.exporter.notification;

import lombok.extern.slf4j.Slf4j;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;

/**
 * Email notification channel implementation.
 * 
 * Sends alerts via email using Spring's JavaMailSender with
 * formatted subject lines and detailed message content.
 * 
 * @author Netflexity
 * @version 1.0.0
 */
@Slf4j
public class EmailNotificationChannel implements NotificationChannel {

    private final String name;
    private final String toEmail;
    private final String fromEmail;
    private final JavaMailSender mailSender;

    public EmailNotificationChannel(String name, String toEmail, String fromEmail, JavaMailSender mailSender) {
        this.name = name;
        this.toEmail = toEmail;
        this.fromEmail = fromEmail;
        this.mailSender = mailSender;
    }

    @Override
    public void send(MonitorAlert alert) throws NotificationException {
        if (!isConfigured()) {
            throw new NotificationException("Email channel not properly configured");
        }

        try {
            SimpleMailMessage message = new SimpleMailMessage();
            message.setFrom(fromEmail);
            message.setTo(toEmail);
            message.setSubject(buildEmailSubject(alert));
            message.setText(buildEmailBody(alert));
            
            mailSender.send(message);
            
            log.debug("Sent email notification for monitor {} to {}", alert.getMonitorName(), toEmail);
            
        } catch (Exception e) {
            throw new NotificationException("Failed to send email notification: " + e.getMessage(), e);
        }
    }

    @Override
    public String getType() {
        return "email";
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public boolean isConfigured() {
        return toEmail != null && !toEmail.trim().isEmpty() &&
               fromEmail != null && !fromEmail.trim().isEmpty() &&
               mailSender != null;
    }

    /**
     * Build email subject line
     */
    private String buildEmailSubject(MonitorAlert alert) {
        return String.format("[%s] Anypoint MQ Alert: %s - %s",
            alert.getSeverity(),
            alert.getMonitorName(),
            alert.getQueueName());
    }

    /**
     * Build detailed email body
     */
    private String buildEmailBody(MonitorAlert alert) {
        StringBuilder body = new StringBuilder();
        
        body.append("Anypoint MQ Monitor Alert\n");
        body.append("========================\n\n");
        
        body.append("Monitor: ").append(alert.getMonitorName()).append("\n");
        body.append("Severity: ").append(alert.getSeverity()).append("\n");
        body.append("Queue: ").append(alert.getQueueName()).append("\n");
        body.append("Environment: ").append(alert.getEnvironmentName()).append("\n");
        body.append("Region: ").append(alert.getRegion()).append("\n");
        body.append("Triggered At: ").append(alert.getTriggeredAt()).append("\n\n");
        
        body.append("Alert Details:\n");
        body.append("--------------\n");
        body.append("Message: ").append(alert.getMessage()).append("\n");
        body.append("Current Value: ").append(String.format("%.1f", alert.getCurrentValue())).append("\n");
        body.append("Threshold Value: ").append(String.format("%.1f", alert.getThresholdValue())).append("\n\n");
        
        if (alert.getMetadata() != null && !alert.getMetadata().isEmpty()) {
            body.append("Additional Information:\n");
            body.append("----------------------\n");
            alert.getMetadata().forEach((key, value) -> 
                body.append(key).append(": ").append(value).append("\n"));
            body.append("\n");
        }
        
        body.append("This alert was generated by the Anypoint MQ Prometheus Exporter.\n");
        body.append("Please check your monitoring dashboard for more details.\n");
        
        return body.toString();
    }
}